

INSERT INTO KING_DOM(ID,NAME,CAPITAL) VALUES(11,'蜀','成都');

INSERT INTO USR (ID,NAME,KINGDOM_ID) VALUES(1,'刘备',1); --,'成都'
INSERT INTO USR (ID,NAME,KINGDOM_ID) VALUES(2,'关羽',2); --,'荆州'
INSERT INTO USR (ID,NAME,KINGDOM_ID) VALUES(3,'张飞',3);--,'西乡'